## Sample .travis.yml file for use with metacran/r-builder
## See https://github.com/metacran/r-builder for details.

language: c
sudo: required

before_install:
  - curl -OL https://raw.githubusercontent.com/metacran/r-builder/master/pkg-build.sh
  - chmod 755 pkg-build.sh
  - ./pkg-build.sh bootstrap

install:
  - sudo apt-get install libgdal1-dev libproj-dev
  - ./pkg-build.sh install_github SEEG-Oxford/seegSDM andrewzm/INLA
  - ./pkg-build.sh install_deps

script:
  - ./pkg-build.sh run_tests

after_failure:
  - ./pkg-build.sh dump_logs

notifications:
  email:
    on_success: change
    on_failure: change

env:
  matrix:
    - RVERSION=oldrel
      R_CHECK_ARGS="--no-manual"
    - RVERSION=release
      R_CHECK_ARGS="--no-manual"
    - RVERSION=devel
      R_CHECK_ARGS="--no-manual"

